Header header

float32 time_boot_ms # Timestamp (milliseconds since system boot)
float32 lat # Latitude, expressed as meters * 10^7
float32 lon # Longitude, expressed as meters * 10^7
float32 alt # Altitude, expressed as meters * 1000 (millimeters) above MSL
float32 relative_alt # Altitude above ground, expressed as meters * 1000 (millimeters)
float32 vx # Ground X speed (latitude), expressed as meters per second * 100
float32 vy # Ground Y speed (longitude), expressed as meters per second * 100
float32 vz # Ground Z speed (altitude), expressed as meters per second * 100
float32 hdg # Compass heading, expressed in degrees * 100
